function generate(json: object): string {
  const jsons = JSON.stringify(json, null, 2);
  return `// This is an automatically generated file! Do not edit!
// Edit the source at: https://docs.google.com/spreadsheets/d/1ughCy983eK-SPIcDYPsjOitVZzY10WdI2MGGrmxzxF4/pubhtml
// Generated by Gruntfile.js:preloadSpreadsheet
// key: v0.2
'use strict';

try {
  angular.module('swarmSpreadsheetPreload');
  //console.log('secondv0.2');
}
catch (e) {
  // module not yet initialized by some other module, we're the first
  angular.module('swarmSpreadsheetPreload', []);
  //console.log('firstv0.2');
}
angular.module('swarmSpreadsheetPreload').value('spreadsheetPreload-v0.2', ${jsons})`;
}
